### ISSUE TITLE
Pupeteer error when building in azure

### ISSUE THREAD

**Issue by waltergpc** [ChappIO/gatsby-remark-mermaid#18]
I am trying to push and build a site into azure. The site is working nice in my local but when it is pushed to azure it throws this error : 
```
/github/workspace/node_modules/puppeteer/.local-chromium/linux-1011831/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

The build is being done in a docker image and I am not sure how to fix it, I have seen some troubleshooting for Docker and apparently I need to install last version of chromium browsers with apt-get.  Has anyone has an example with the docker build steps and the chromium steps in it? Or another workaround with azure?

**Comment by DanInProgress** [comment]
when you say it's working locally, you mean that it's working locally *within* a docker container or on your host machine? the failure is occuring within an azure pipeline? can you link to the configuration/post it here?

My basic read is that it looks like libnss3 is not present on the machine. chrome relies on this, and the npm package that installs pupeteer *does* fetch a version of chrome, but that expects some dependencies to be present (libnss3 is probably one of those)

**Comment by remcohaszing** [comment]
This package used Puppeteer under the hood. Please see the [Puppeteer troubleshooting guide](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix) for this. The exact steps needed depend on the Docker image used.
