### ISSUE TITLE
'path/to/chrome/executable' ?!?

### ISSUE THREAD

**Issue by lukwe** [ChappIO/gatsby-remark-mermaid#20]
actually … where one is supposed to find the correct 'path/to/chrome/executable' ? this is not an issue with the code but the readme.md could be more helpful on this!

**Comment by remcohaszing** [comment]
I don’t understand what’s unclear about it? If you [scroll a bit down](https://github.com/remcohaszing/gatsby-remark-mermaid#options) you’ll find:

> String path to the chrome executable that puppeteer uses to render the mermaid diagrams to SVGs.

How you find this path, depends on your system and how you installed Chrome. E.g. to find it on Linux, run:

```sh
which google-chrome
```

**Comment by lukwe** [comment]
'which google-chrome' returns nothing (MAc OS) I then got it by right-clicking on the gChrome icon in the Applications folders to 'Show Package contents' and then proceeded into 'contents/MacOS/Google\ Chrome'

Thanks anyhow ..

Cheers, Luca

PS: hard-coding this path into gatsby-config.js is not the correct way to manage a repository for a gatsby site , devs on other systems will be unable to run 'gatsby build / develop ' successfully.

Apparently 'chrome-launcher' node.js module can be used to search any OS for the path, shouldn't it be included in the dependencies ??
