### ISSUE TITLE
Upgrade remark-mermaidjs to latest v6.0.0 to support mermaid v11+

### ISSUE THREAD

**Issue by amamenko** [ChappIO/gatsby-remark-mermaid#21]
It appears that `gatsby-remark-mermaid` is locked into v10 of `mermaid`:

From the dependencies of `gatsby-remark-mermaid`'s `package.json`:
> "dependencies": {
>     "remark-mermaidjs": "^5.0.0",
>    ...

From the dependencies of`remark-mermaidjs`'s `5.0.0` `package.json`:
>  "dependencies": {
>     ...
>     "mermaid-isomorphic": "^2.0.0",
>     ...
>   }

Further looking into `mermaid-isomorphic`'s `2.0.0` `package.json`:
> "dependencies": {
>    ...
>     "mermaid": "^10.0.0",
>     ...
>   }

This is preventing the use of `mermaid` v11+ features such as [architecture](https://mermaid.js.org/syntax/architecture.html) and [packet](https://mermaid.js.org/syntax/packet.html). 

Would appreciate bumping the `remark-mermaidjs` package used by `gatsby-remark-mermaid` to the latest version [6.0.0](https://www.npmjs.com/package/remark-mermaidjs/v/6.0.0).

**Comment by remcohaszing** [comment]
I’ll get to it soon. `mermaid-isomorphic` [3.0.0](https://github.com/remcohaszing/mermaid-isomorphic/releases/tag/v3.0.0) was just released.

**Comment by amamenko** [comment]
Awesome, thanks @remcohaszing!
